spring:
  application:
    name: bucket-service

  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        profile:
          name: s3-config

    config:
      s3:
        bucket:
          default: ${AWS_S3_BUCKET}

springdoc:
  api-docs:
    path: /swagger-doc/v3/api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-doc/swagger-ui.html
